name: Build and Sync .vitepress/dist to deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 使用 Node.js 18 版本

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: deploy
          path: deploy-branch

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy .vitepress/dist to deploy
        run: |
          cp -r .vitepress/dist/* deploy-branch/
          cd deploy-branch
          git add .
          git commit -m "Update .vitepress/dist directory"
          git push origin deploy

      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.FROM_EMAIL_ADDRESS }}
          password: ${{ secrets.FROM_EMAIL_TOKEN }}
          subject: "Deploy success！"
          body: "The deploy branch has been updated."
          from: "github"
          to: ${{ secrets.TO_EMAIL_ADDRESS }}

      - name: Clean up
        run: rm -rf deploy-branch
