name: 构建
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - master

  # pull_request:
  # branches: [ master,main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: building...
        run: |
          pnpm build
      - name: 更新数据
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: master
          folder: .