name: 发布文章
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - master

  # pull_request:
  # branches: [ master,main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          node-version: "16.x"
      - name: npm包安装
        run: pnpm install
      - name: 开始任务
        run: |
          node build.js
      - name: 更新数据
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main
          folder: .